### ISSUE TITLE
is there some config for dropdown ul

### ISSUE THREAD

**Issue by shuang920** [One-com/knockout.autocomplete#10]
I think I meet some question.

When I load autocomplte to my personal project, if I want always make dropdown ui below the input elements, how do i to set it, it makes me crazy.

**Comment by sunesimonsen** [comment]
Have you looked at:
https://github.com/One-com/knockout.autocomplete/blob/master/examples/TimeComplete.js

**Comment by shuang920** [comment]
Maybe I send wrong message to this issue. 

The point to my ask is that, when the document scrolltop change, is there some way to make dorpdown always fix parent element?

I get an screenshot for my question.


![Uploading 360截图20150925152350760.jpg…]()

**Comment by sunesimonsen** [comment]
I can't see your screenshot.

**Comment by shuang920** [comment]
![360 20150925152350760](https://cloud.githubusercontent.com/assets/13883597/10095633/beb9fb62-639d-11e5-8d32-ceb8627681ec.jpg)

**Comment by sunesimonsen** [comment]
Are you on the latest version? I think I fixed a problem recently related to scrolling.

**Comment by shuang920** [comment]
Thank you very much, I found the reason. :+1:  Thanks.

**Comment by sunesimonsen** [comment]
NP glad I could help.
