### ISSUE TITLE
Compatibility with KnockOut JS 3.4.0

### ISSUE THREAD

**Issue by zalaps** [One-com/knockout.autocomplete#19]
I was trying to use it with version 3.4.0. I think it's not working. I may be wrong.
Here is the fiddle. https://jsfiddle.net/ywvj679q/

**Comment by gitkyle** [comment]
It works fine, you just need to point your KO dependency to a CDN serving via HTTPS: https://jsfiddle.net/kzh3umhL/3/

**Comment by zalaps** [comment]
Thanks!
